[package]
name = "RustGDN"
version = "0.1.0"
edition = "2021"

[net]
git-fetch-with-cli = true

[dependencies]
serde_json = "1.0.120"
macrometa_sdk = {  git = "ssh://git@github.com/Macrometacorp/macrometa-api-rust-sdk.git", branch="master" }

tokio = "1.38.0"
dotenv = "0.15.0"
